---

version: '3.8'

services:
  main:
    build:
      dockerfile: Dockerfile.prod
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./.aws/credentials:/root/.aws/credentials:ro
    environment:
      - PYTHONUNBUFFERED=1
      - BASE_IMAGE_TAG=3.12.2-slim-bookworm
      - DOCKER_ENV_VARS=on
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; response = requests.get('http://localhost:8501/_stcore/health'); exit(0) if response.status_code == 200 else exit(1)\" "]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  nginx:
    image: 991404956194.dkr.ecr.us-west-2.amazonaws.com/nrel-split-nginx:1.29.5.1
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - main
    links:
      - main
    environment:
      NGINX_BACKEND_HOST: main
      NGINX_BACKEND_PORT: "8501"
      NGINX_NO_STATIC: "on"
      NGINX_WEBSOCKET_UPGRADE: "on"
      NGINX_WEBSOCKET_READ_TIMEOUT: "3m"
      NGINX_WEBSOCKET_SEND_TIMEOUT: "3m"
      NGINX_HEADERS_CONTENT_SECURITY_POLICY: "frame-ancestors 'self' *.nrel.gov *.nlr.gov;"
      NGINX_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      NGINX_VHOST_PRESET: http-proxy
      NGINX_CLIENT_MAX_BODY_SIZE: "1024m"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_FASTCGI_BUFFERING: "off"
      NGINX_GROUP: "www-data"
      NGINX_USER: "www-data"
      NGINX_MOREHEADERS_ENABLED: "on"
      NGINX_SERVER_TOKENS: "off"
      NGINX_HIDE_50x_ERRORS: "on"
      NGINX_HIDE_50x_ERROR_CODES: "500 501 502 503 504 505 506 507 508 510 511 =404"
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_STRICT_TRANSPORT_SECURITY: "max-age=63072000; includeSubDomains; preload"
      NGINX_EXPECT_CT: "enforce, max-age=7776000, report-uri='https://ABSOLUTE_REPORT_URL'"
      NGINX_REFERRER_POLICY: "origin"
      NGINX_X_FRAME_OPTIONS: SAMEORIGIN
      NGINX_LOG_FORMAT_OVERRIDE: '$$remote_addr - $$remote_user [$$time_local] "$$request" $$status $$body_bytes_sent "$$http_referer""$$http_user_agent""$$http_x_forwarded_for"'
      DOCKER_ENV_VARS: "on"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/_stcore/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.entrypoints=web"
      - "traefik.http.middlewares.${PROJECT_NAME}_https_nginx.redirectscheme.scheme=https"
      - "traefik.http.routers.${PROJECT_NAME}_https_nginx.rule=Host(`${PROJECT_NAME}.docker.localhost`)"
      - "traefik.http.routers.${PROJECT_NAME}_https_nginx.entrypoints=web-secure"
      - "traefik.http.routers.${PROJECT_NAME}_https_nginx.tls=true"

  traefik:
    image: traefik:v2.11.31
    container_name: "${PROJECT_NAME}_traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - '--providers.file.filename=/etc/traefik/dynamic_conf/conf.yml'
      - --providers.file.watch=true
      - "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.dynamic.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - ./certs/:/certs/
